// GENERATED by scripts/engraving-data.mjs from public/engraving/. Do not edit.
// Run `node scripts/engraving-data.mjs` after changing stamps.json or a stamp.
//
// Per stamp: id and name (from stamps.json), the SVG file, and the drawn
// size in inches for each size (the longest side printed on Deborah's
// sheet, the other side from the SVG's proportions).
export const ENGRAVING_STAMPS = [
  {"id":"arrowhead","name":"Arrowhead","file":"/engraving/stamps/arrowhead.svg","large":{"w":0.713,"h":1},"small":{"w":0.535,"h":0.75}},
  {"id":"crossed-guns","name":"Crossed Guns","file":"/engraving/stamps/crossed-guns.svg","large":{"w":0.985,"h":1},"small":{"w":0.739,"h":0.75}},
  {"id":"longhorn","name":"Longhorn","file":"/engraving/stamps/longhorn.svg","large":{"w":1.2,"h":0.728},"small":{"w":0.9,"h":0.546}},
  {"id":"horse","name":"Horse","file":"/engraving/stamps/horse.svg","large":{"w":1,"h":0.783},"small":{"w":0.75,"h":0.587}},
  {"id":"bison","name":"Bison","file":"/engraving/stamps/bison.svg","large":{"w":1,"h":0.713},"small":{"w":0.75,"h":0.535}},
  {"id":"horse-head","name":"Horse Head","file":"/engraving/stamps/horse-head.svg","large":{"w":0.794,"h":1},"small":{"w":0.596,"h":0.75}},
  {"id":"rising-sun","name":"Rising Sun","file":"/engraving/stamps/rising-sun.svg","large":{"w":1.1,"h":0.697},"small":{"w":0.8,"h":0.507}},
  {"id":"mountains","name":"Mountains","file":"/engraving/stamps/mountains.svg","large":{"w":1,"h":0.623},"small":{"w":0.75,"h":0.467}},
  {"id":"bucking-bronco","name":"Bucking Bronco","file":"/engraving/stamps/bucking-bronco.svg","large":{"w":1,"h":0.993},"small":{"w":0.75,"h":0.745}},
  {"id":"cowboy-boot","name":"Cowboy Boot","file":"/engraving/stamps/cowboy-boot.svg","large":{"w":0.869,"h":1},"small":{"w":0.651,"h":0.75}},
  {"id":"cowboy-hat","name":"Cowboy Hat","file":"/engraving/stamps/cowboy-hat.svg","large":{"w":1,"h":0.68},"small":{"w":0.75,"h":0.51}},
  {"id":"cross","name":"Cross","file":"/engraving/stamps/cross.svg","large":{"w":0.875,"h":1},"small":{"w":0.656,"h":0.75}},
  {"id":"horseshoe","name":"Horseshoe","file":"/engraving/stamps/horseshoe.svg","large":{"w":0.887,"h":0.9},"small":{"w":0.69,"h":0.7}},
  {"id":"medium-star","name":"Medium Star","file":"/engraving/stamps/medium-star.svg","large":{"w":1,"h":0.944},"small":{"w":0.75,"h":0.708}},
  {"id":"snake","name":"Snake","file":"/engraving/stamps/snake.svg","large":{"w":0.639,"h":1.1},"small":{"w":0.465,"h":0.8}},
  {"id":"cactus","name":"Cactus","file":"/engraving/stamps/cactus.svg","large":{"w":0.711,"h":1},"small":{"w":0.533,"h":0.75}},
  {"id":"heart-outline","name":"Heart Outline","file":"/engraving/stamps/heart-outline.svg","large":{"w":1.1,"h":1.005},"small":{"w":0.8,"h":0.731}},
  {"id":"heart-silhouette","name":"Heart Silhouette","file":"/engraving/stamps/heart-silhouette.svg","large":{"w":0.9,"h":0.82},"small":{"w":0.5,"h":0.456}},
  {"id":"feather","name":"Feather","file":"/engraving/stamps/feather.svg","large":{"w":0.626,"h":1.2},"small":{"w":0.47,"h":0.9}},
  {"id":"lightning-bolt","name":"Lightning Bolt","file":"/engraving/stamps/lightning-bolt.svg","large":{"w":0.699,"h":1},"small":{"w":0.524,"h":0.75}},
  {"id":"spade","name":"Spade","file":"/engraving/stamps/spade.svg","large":{"w":0.933,"h":1},"small":{"w":0.747,"h":0.8}},
  {"id":"arrow","name":"Arrow","file":"/engraving/stamps/arrow.svg","large":{"w":1,"h":0.493},"small":{"w":0.75,"h":0.369}},
  {"id":"simple-cross","name":"Simple Cross","file":"/engraving/stamps/simple-cross.svg","large":{"w":0.816,"h":1},"small":{"w":0.612,"h":0.75}},
  {"id":"wave","name":"Wave","file":"/engraving/stamps/wave.svg","large":{"w":1.5,"h":0.683},"small":{"w":1.1,"h":0.501}},
  {"id":"star-outline","name":"Star Outline","file":"/engraving/stamps/star-outline.svg","large":{"w":1,"h":0.971},"small":{"w":0.75,"h":0.729}},
  {"id":"antler-left","name":"Antler Left","file":"/engraving/stamps/antler-left.svg","large":{"w":0.874,"h":1},"small":{"w":0.656,"h":0.75}},
  {"id":"antler-right","name":"Antler Right","file":"/engraving/stamps/antler-right.svg","large":{"w":0.867,"h":1},"small":{"w":0.65,"h":0.75}},
  {"id":"crescent-moon","name":"Crescent Moon","file":"/engraving/stamps/crescent-moon.svg","large":{"w":0.977,"h":1},"small":{"w":0.733,"h":0.75}},
  {"id":"olive-branch","name":"Olive Branch","file":"/engraving/stamps/olive-branch.svg","large":{"w":1.327,"h":1.5},"small":{"w":1.062,"h":1.2}},
  {"id":"longhorn-skull","name":"Longhorn Skull","file":"/engraving/stamps/longhorn-skull.svg","large":{"w":1,"h":0.905},"small":{"w":0.75,"h":0.679}},
];
