// GENERATED by scripts/engraving-data.mjs from public/engraving/. Do not edit.
// The stamp ids only, so pricing.js can validate without the full list.
export const ENGRAVING_STAMP_IDS = ["arrowhead","crossed-guns","longhorn","horse","bison","horse-head","rising-sun","mountains","bucking-bronco","cowboy-boot","cowboy-hat","cross","horseshoe","medium-star","snake","cactus","heart-outline","heart-silhouette","feather","lightning-bolt","spade","arrow","simple-cross","wave","star-outline","antler-left","antler-right","crescent-moon","olive-branch","longhorn-skull"];
