// Generate the stamp modules from public/engraving/.
//
//   node scripts/engraving-data.mjs          write them
//   node scripts/engraving-data.mjs --check  exit 1 if one is out of date
//
//   src/shop/engravingStamps.js    every stamp: name, file, drawn size. Loaded
//                                  on demand (the Brand it step, the drawing,
//                                  the server's emails)
//   src/shop/engravingStampIds.js  the ids only, for pricing.js, which is in
//                                  the main bundle and only needs to validate
//
// public/engraving/ is the source (stamps.json and the SVGs) and is never
// written to. The generated module is plain data, so pricing.js, which the
// server runs, can import it without reading files at runtime.
//
// SIZES. stamps.json gives two numbers per size "as printed on Deborah's
// sheet", but their order is not consistent (Longhorn large is 0.6 x 1.2,
// height first; Horse large is 1 x 0.7, width first). So the larger number
// is taken as the stamp's longest side, and the other side follows the
// SVG's own proportions. That never draws a stamp larger than the sheet's
// longest measure, and keeps every stamp undistorted.
//
// EXCEPTIONS (BOX_OVERRIDES) are stamps whose sheet measure is not their box:
// the Olive Branch is a diagonal branch, and its 1.5 in is the length of the
// branch, so its box is set square by hand. The drawing fits the SVG inside
// the box without stretching it.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const SRC = `${root}public/engraving`;
const OUT = `${root}src/shop/engravingStamps.js`;
const OUT_IDS = `${root}src/shop/engravingStampIds.js`;

// inches per size, as a square box { w: n, h: n }
export const BOX_OVERRIDES = {
  "olive-branch": { large: 1.1, small: 0.9 },
};

const round = (n) => Math.round(n * 1000) / 1000;

export function buildStampData() {
  const { stamps } = JSON.parse(readFileSync(`${SRC}/stamps.json`, "utf8"));
  return stamps.map((s) => {
    const svg = readFileSync(`${SRC}/${s.file}`, "utf8");
    const vb = svg.match(/viewBox="([^"]+)"/);
    if (!vb) throw new Error(`${s.file} has no viewBox`);
    const [, , w, h] = vb[1].trim().split(/[\s,]+/).map(Number);
    const aspect = w / h;
    const inches = (size) => {
      const box = BOX_OVERRIDES[s.id]?.[size];
      if (box) return { w: box, h: box };
      const longest = Math.max(...s.sizeInches[size]);
      return aspect >= 1 ? { w: round(longest), h: round(longest / aspect) } : { w: round(longest * aspect), h: round(longest) };
    };
    return {
      id: s.id,
      name: s.label,
      file: `/engraving/${s.file}`,
      large: inches("large"),
      small: inches("small"),
    };
  });
}

export function renderModule(data) {
  const rows = data.map((s) => `  ${JSON.stringify(s)},`).join("\n");
  return `// GENERATED by scripts/engraving-data.mjs from public/engraving/. Do not edit.
// Run \`node scripts/engraving-data.mjs\` after changing stamps.json or a stamp.
//
// Per stamp: id and name (from stamps.json), the SVG file, and the box in
// inches for each size (the longest side printed on Deborah's sheet, the
// other side from the SVG's proportions; Olive Branch is set by hand, see
// BOX_OVERRIDES in the script).
export const ENGRAVING_STAMPS = [
${rows}
];
`;
}

export function renderIdsModule(data) {
  return `// GENERATED by scripts/engraving-data.mjs from public/engraving/. Do not edit.
// The stamp ids only, so pricing.js can validate without the full list.
export const ENGRAVING_STAMP_IDS = ${JSON.stringify(data.map((s) => s.id))};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const data = buildStampData();
  const files = [
    [OUT, renderModule(data)],
    [OUT_IDS, renderIdsModule(data)],
  ];
  if (process.argv.includes("--check")) {
    const stale = files.filter(([f, text]) => {
      try {
        return readFileSync(f, "utf8") !== text;
      } catch {
        return true;
      }
    });
    if (stale.length) {
      console.error(`Out of date: ${stale.map(([f]) => f).join(", ")}. Run: node scripts/engraving-data.mjs`);
      process.exit(1);
    }
    console.log("stamp modules are up to date");
  } else {
    for (const [f, text] of files) {
      writeFileSync(f, text);
      console.log(`wrote ${f}`);
    }
  }
}
