// Generate src/shop/engravingStamps.js from public/engraving/.
//
//   node scripts/engraving-data.mjs          write the module
//   node scripts/engraving-data.mjs --check  exit 1 if it is out of date
//
// public/engraving/ is the source (stamps.json and the SVGs) and is never
// written to. The generated module is plain data, so pricing.js, which the
// server runs, can import it without reading files at runtime.
//
// SIZES. stamps.json gives two numbers per size "as printed on Deborah's
// sheet", but their order is not consistent (Longhorn large is 0.6 x 1.2,
// height first; Horse large is 1 x 0.7, width first). So the larger number
// is taken as the stamp's longest side, and the other side follows the
// SVG's own proportions. That never draws a stamp larger than the sheet's
// longest measure, and keeps every stamp undistorted.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const SRC = `${root}public/engraving`;
const OUT = `${root}src/shop/engravingStamps.js`;

const round = (n) => Math.round(n * 1000) / 1000;

export function buildStampData() {
  const { stamps } = JSON.parse(readFileSync(`${SRC}/stamps.json`, "utf8"));
  return stamps.map((s) => {
    const svg = readFileSync(`${SRC}/${s.file}`, "utf8");
    const vb = svg.match(/viewBox="([^"]+)"/);
    if (!vb) throw new Error(`${s.file} has no viewBox`);
    const [, , w, h] = vb[1].trim().split(/[\s,]+/).map(Number);
    const aspect = w / h;
    const inches = (size) => {
      const longest = Math.max(...s.sizeInches[size]);
      return aspect >= 1 ? { w: round(longest), h: round(longest / aspect) } : { w: round(longest * aspect), h: round(longest) };
    };
    return {
      id: s.id,
      name: s.label,
      file: `/engraving/${s.file}`,
      large: inches("large"),
      small: inches("small"),
    };
  });
}

export function renderModule(data) {
  const rows = data.map((s) => `  ${JSON.stringify(s)},`).join("\n");
  return `// GENERATED by scripts/engraving-data.mjs from public/engraving/. Do not edit.
// Run \`node scripts/engraving-data.mjs\` after changing stamps.json or a stamp.
//
// Per stamp: id and name (from stamps.json), the SVG file, and the drawn
// size in inches for each size (the longest side printed on Deborah's
// sheet, the other side from the SVG's proportions).
export const ENGRAVING_STAMPS = [
${rows}
];
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const text = renderModule(buildStampData());
  if (process.argv.includes("--check")) {
    const current = readFileSync(OUT, "utf8");
    if (current !== text) {
      console.error("src/shop/engravingStamps.js is out of date. Run: node scripts/engraving-data.mjs");
      process.exit(1);
    }
    console.log("engravingStamps.js is up to date");
  } else {
    writeFileSync(OUT, text);
    console.log(`wrote ${OUT}`);
  }
}
